file(GLOB_RECURSE UI_SOURCE_FILES
    "${SOURCE_DIR}/src/app/*.cpp"
    "${SOURCE_DIR}/src/ui/*.cpp"
)

foreach(SOURCE_FILE IN LISTS UI_SOURCE_FILES)
    file(READ "${SOURCE_FILE}" SOURCE_CONTENT)
    if(SOURCE_CONTENT MATCHES "QMessageBox::(warning|information|question|about)[(]")
        message(FATAL_ERROR "Blocking static QMessageBox call found in ${SOURCE_FILE}")
    endif()
    if(SOURCE_CONTENT MATCHES "[.]exec[(][)]")
        message(FATAL_ERROR "Nested modal event loop found in ${SOURCE_FILE}")
    endif()
    if(SOURCE_CONTENT MATCHES "QFileDialog::getSaveFileName")
        message(FATAL_ERROR "Blocking static file dialog found in ${SOURCE_FILE}")
    endif()
    if(SOURCE_CONTENT MATCHES "\n[ \t]*setEnabled[(]false[)]")
        message(FATAL_ERROR "Whole-window disabling found in ${SOURCE_FILE}")
    endif()
    if(SOURCE_CONTENT MATCHES "QtConcurrent::run[(][ \t\r\n]*\\[bridge")
        message(FATAL_ERROR "Go work must use the bridge-owned thread pool in ${SOURCE_FILE}")
    endif()
endforeach()

file(READ "${SOURCE_DIR}/src/bridge/GoBridge.cpp" BRIDGE_SOURCE)
if(BRIDGE_SOURCE MATCHES "globalInstance[(][)][^\n]*waitForDone")
    message(FATAL_ERROR "GoBridge shutdown must not wait for unrelated global thread-pool work")
endif()

file(READ "${SOURCE_DIR}/src/app/AppController.cpp" APP_CONTROLLER_SOURCE)
if(NOT APP_CONTROLLER_SOURCE MATCHES "QEvent::Quit")
    message(FATAL_ERROR "Application-level Quit events must enter the guarded restore flow")
endif()

file(READ "${SOURCE_DIR}/src/ui/Dialogs.cpp" DIALOG_SOURCE)
string(FIND "${DIALOG_SOURCE}" "StartProtectionProxy" START_PROXY_POSITION)
string(FIND "${DIALOG_SOURCE}" "SaveProtectionConfigFFI" SAVE_CONFIG_POSITION)
if(START_PROXY_POSITION LESS 0 OR SAVE_CONFIG_POSITION LESS 0 OR SAVE_CONFIG_POSITION LESS START_PROXY_POSITION)
    message(FATAL_ERROR "Protection configuration must only be persisted as enabled after the proxy starts")
endif()
if(DIALOG_SOURCE MATCHES "color[ ]*[+][ ]*QStringLiteral[(]\"33\"[)]")
    message(FATAL_ERROR "Qt colors must not use CSS-style trailing alpha values")
endif()
